-- Variable tipo bean, remplaza variable de sustitucion y no tiene que ser precompliada 2 veces
-- podemos tener todas las v bean que queramos

SET SERVEROUTPUT ON;

DECLARE
  RESULTADO NUMBER;
BEGIN
    SELECT COUNT(*) INTO RESULTADO FROM EMPLOYEES WHERE DEPARTMENT_ID = :X;
    
    DBMS_OUTPUT.PUT_LINE(RESULTADO);
END;
/

-- Ejemplo uso variables bean

DECLARE 
    RESULTADO NUMBER;
    SALARIO NUMBER;
BEGIN
  SELECT COUNT(*) INTO RESULTADO FROM EMPLOYEES WHERE EMPLOYEE_ID = :ID;
  
  IF RESULTADO = 0 THEN
    DBMS_OUTPUT.PUT_LINE('NO EXISTE EL TRABAJADOR ID: '|| :ID);
  ELSE
    DBMS_OUTPUT.PUT_LINE('EXISTEN'||RESULTADO||'CON ID'|| :ID);
    DBMS_OUTPUT.PUT_LINE('SE ACTUALIZARA EL SUELDO DEL TRABAJADOR '|| :ID);
    DBMS_OUTPUT.PUT_LINE('EN UN: '|| :PORCENTAJE||'%');
    DBMS_OUTPUT.PUT('EL SALARIO ACTUAL ES: ');
    
    SELECT SALARY INTO SALARIO FROM EMPLOYEES WHERE EMPLOYEE_ID = :ID;
    DBMS_OUTPUT.PUT_LINE(SALARIO);
    
    UPDATE EMPLOYEES
    SET SALARY = ((SALARY * :PORCENTAJE)/ 100)+ SALARY
    WHERE EMPLOYEE_ID = :ID;
    
    SELECT SALARY INTO SALARIO FROM EMPLOYEES WHERE EMPLOYEE_ID = :ID;
    
    DBMS_OUTPUT.PUT_LINE('EL SALARIO ACTUALIZADO ES: '||SALARIO);
  END IF;
END;
/
