set serveroutput on;

--Case texto
DECLARE
  TEXTO VARCHAR2(10);
BEGIN
  TEXTO := '&INGRESE_TEXTO';
CASE UPPER(TEXTO)
  WHEN 'HOLA' THEN
   DBMS_OUTPUT.PUT_LINE('HAS INGRESADO HOLA');
  WHEN 'ADIOS' THEN
   DBMS_OUTPUT.PUT_LINE('HAS INGRESADO ADIOS');
  ELSE
   DBMS_OUTPUT.PUT_LINE('NO INGRESASTE NINGUNA DE LAS OPCIONES');
  END CASE;
 END;
 /
 
 --Case Numero con conversion, ERROR DE TIPO
DECLARE
  TEXTO VARCHAR2(10);
BEGIN
  TEXTO := '&INGRESE_TEXTO';
CASE UPPER(TEXTO)
  WHEN 1 THEN
   DBMS_OUTPUT.PUT_LINE('HAS INGRESADO UNO');
  WHEN 2 THEN
   DBMS_OUTPUT.PUT_LINE('HAS INGRESADO DOS');
  ELSE
   DBMS_OUTPUT.PUT_LINE('NO INGRESASTE NINGUNA DE LAS OPCIONES');
  END CASE;
 
  
END;
/

 --Case Numero con conversion
DECLARE
  NUMERO NUMBER;
BEGIN
  NUMBER := '&INGRESE_TEXTO';
CASE UPPER(NUMBER)
  WHEN 1 THEN
   DBMS_OUTPUT.PUT_LINE('HAS INGRESADO UNO');
  WHEN 2 THEN
   DBMS_OUTPUT.PUT_LINE('HAS INGRESADO DOS');
  ELSE
   DBMS_OUTPUT.PUT_LINE('NO INGRESASTE NINGUNA DE LAS OPCIONES');
  END CASE;
 
  
END;
/


-- EJECERICIO
/*
CREAR BLOQUE ANONIMO MEDIANTE EL CUAL CONSULTARAN LA CANTIDAD DE PERSONAS EN LA TABLA EMPLYESS QUE POSEAN UN NOMBRE X,
SI ES 1 INDICAN, QUE SOLO POSEEN 1 EMPLEADO, SI ES 2: ES UNA PAREJA AFORTUNADA, SI ES 0: NO HAY AFORTUNADOS
ELSE: ES IMPOSIBLE QUE MEDIR LO SOLICITADO
*/
DECLARE
  V_CANTIDAD NUMBER;
  V_NOMBRES VARCHAR2(20);
BEGIN

 V_NOMBRES := '&INGRESE UN NOMBRE';
 
SELECT COUNT(*) INTO V_CANTIDAD
FROM EMPLOYEES
WHERE UPPER(FIRST_NAME) LIKE UPPER(V_NOMBRES);
  
  CASE V_CANTIDAD
  WHEN 1 THEN
   DBMS_OUTPUT.PUT_LINE(' SOLO HAY UNO');
  WHEN 2 THEN
   DBMS_OUTPUT.PUT_LINE(' ES UNA PAREJA AFORTUNADA');
  ELSE
   DBMS_OUTPUT.PUT_LINE(' NO HAY AFORTUNADOS');
  END CASE;
 
  
END;
/

select * from employees;

