DECLARE
  NUMERO NUMBER := '&INGRESE_NUMERO';
BEGIN
  --DESDE I IGUAL A NUMERO HASTA 300
  FOR I IN NUMERO ..300 LOOP
    DBMS_OUTPUT.PUT_LINE(I);
  END LOOP;
END;
/

DECLARE
  NUMERO NUMBER := '&INGRESE_NUMERO';
BEGIN
  --DESDE I HASTA NUMERO DESDE 200 
  FOR I IN REVERSE NUMERO ..300 LOOP
    DBMS_OUTPUT.PUT_LINE(I);
  END LOOP;
END;
