DECLARE
  NUMERO NUMBER := '&INGRESE_NUMERO';
BEGIN
  --DESDE I IGUAL A NUMERO HASTA 300
  FOR I IN NUMERO ..300 LOOP
    DBMS_OUTPUT.PUT_LINE(I);
  END LOOP;
END;
/

DECLARE
  NUMERO NUMBER := '&INGRESE_NUMERO';
BEGIN
  --DESDE I HASTA NUMERO DESDE 200 
  FOR I IN REVERSE NUMERO ..300 LOOP
    DBMS_OUTPUT.PUT_LINE(I);
  END LOOP;
END;
/

-- EJEMPLO PRACTICO --
--    REALZIZADO EN USUARIO HR --
SELECT * FROM EMPLOYEES;

DECLARE 
  NUMERO NUMBER;
  MINIMO NUMBER;
  REGISTRO EMPLOYEES%ROWTYPE;
  BEGIN
   
    SELECT MAX(EMPLOYEE_ID) INTO NUMERO FROM EMPLOYEES;
    SELECT MIN(EMPLOYEE_ID) INTO MINIMO FROM EMPLOYEES;
    
    FOR I IN REVERSE MINIMO ..NUMERO LOOP
        SELECT * INTO REGISTRO FROM EMPLOYEES WHERE EMPLOYEE_ID = I;
          DBMS_OUTPUT.PUT_LINE('=============================== ');
          DBMS_OUTPUT.PUT_LINE('NRO REGISTRO: '||REGISTRO.EMPLOYEE_ID);
          DBMS_OUTPUT.PUT_LINE('NOMBRE COMPLETO: '||REGISTRO.FIRST_NAME||' '||REGISTRO.LAST_NAME);
          DBMS_OUTPUT.PUT_LINE('CORREO: '||REGISTRO.EMAIL);
          DBMS_OUTPUT.PUT_LINE('SALARIO: '||TO_CHAR(REGISTRO.SALARY,'$999G999G999'));
    END LOOP;
    
  END;
  /
