DECLARE 
NUMERO NUMBER := 0;

BEGIN
  LOOP
  DBMS_OUTPUT.PUT_LINE(NUMERO);
  NUMERO := NUMERO+1;
    IF NUMERO = 10 THEN
      EXIT;
    END IF;
  END LOOP;
END;
/

--CODIGO 2 --
DECLARE 
NUMERO NUMBER := 0;

BEGIN
  LOOP
  DBMS_OUTPUT.PUT_LINE(NUMERO);
  NUMERO := NUMERO+1;
  EXIT WHEN NUMERO = 10;
   
  END LOOP;
END;
/

--CODIGO 3--
DECLARE 
NUMERO NUMBER := 0;

BEGIN
  LOOP
  DBMS_OUTPUT.PUT_LINE(NUMERO);
  NUMERO := NUMERO+1;
  EXIT WHEN NUMERO = 10 OR NUMERO = 9;
   
  END LOOP;
END;
/

--CODIGO 4--
-- LOOP ETIQUETADO DENTRO DE OTRO LOOP
DECLARE 
  NUMERO1 NUMBER := 0;
  NUMERO2 NUMBER := 0; 
BEGIN
  <<LOOP_EXTERNO>>
  LOOP
    <<LOOP_INTERNO>>
    LOOP
      DBMS_OUTPUT.PUT_LINE('INTERNO '||NUMERO1||' EXTERNO '||NUMERO2);
      NUMERO1 := NUMERO1+1;
      IF NUMERO1 = 5 THEN
        NUMERO1 := 0;
        NUMERO2 := NUMERO2 +1;
      END IF;
      EXIT LOOP_INTERNO WHEN NUMERO1 = 5;
      EXIT LOOP_EXTERNO WHEN NUMERO2 = 3;
    END LOOP;
  END LOOP;
END;
/

--CODIGO 5--
-- LOOP ETIQUETADO DENTRO DE OTRO LOOP
DECLARE 
  NUMERO1 NUMBER := 0;
  NUMERO2 NUMBER := 0; 
BEGIN
  <<LOOP_EXTERNO>>
  LOOP
  NUMERO1 := 0;
    <<LOOP_INTERNO>>
    LOOP
      DBMS_OUTPUT.PUT_LINE('INTERNO '||NUMERO1||' EXTERNO '||NUMERO2);
      NUMERO1 := NUMERO1+1;
     
      EXIT LOOP_INTERNO WHEN NUMERO1 = 5;
      EXIT LOOP_EXTERNO WHEN NUMERO2 = 3;
    END LOOP;
    NUMERO2 := NUMERO2 + 1;
  END LOOP;
END;
/
