--Variables compuestas o  personalizada

--Variable tipo RECORD
SET SERVEROUTPUT ON;

DECLARE
  TYPE OBJ_DATOS IS RECORD(
    NOMBRE VARCHAR2(75) NOT NULL := 'VACIO',
    APELLIDO  VARCHAR2(75) NOT NULL := 'VACIO'
  );
  
  DATO_NOMBRE OBJ_DATOS;  -- La variable dato_nombre es igual a 2 varchar2(75)
BEGIN
  SELECT FIRST_NAME, LAST_NAME INTO DATO_NOMBRE
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = &INGRESE_CODIGO;
  
  DBMS_OUTPUT.PUT_LINE(DATO_NOMBRE.NOMBRE);
  DBMS_OUTPUT.PUT_LINE(DATO_NOMBRE.APELLIDO);
END;
/

  
--variable record que almacene 5 datos
DECLARE
  TYPE PERSONA IS RECORD(
    NOMBRE VARCHAR2(75) NOT NULL := 'VACIO',
    APELLIDO  VARCHAR2(75) NOT NULL := 'VACIO',
    NUMERO  VARCHAR(50)  NOT NULL := 'VACIO',
    FECHA_CONTRATO  DATE NOT NULL := '01/11/2011',
    SUELDO  NUMBER NOT NULL := 0
  );

  DATOS_PERSONA PERSONA;  
  -- La variable datos_persona es detipo persona, igual a los 5 datos que componen a persona
BEGIN

  SELECT FIRST_NAME, LAST_NAME, PHONE_NUMBER, HIRE_DATE, SALARY INTO DATOS_PERSONA
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = &INGRESE_CODIGO;
  
  DBMS_OUTPUT.PUT_LINE( DATOS_PERSONA.NOMBRE);
  DBMS_OUTPUT.PUT_LINE( DATOS_PERSONA.APELLIDO);
    DBMS_OUTPUT.PUT_LINE( DATOS_PERSONA.NUMERO);
  DBMS_OUTPUT.PUT_LINE( DATOS_PERSONA.FECHA_CONTRATO);
    DBMS_OUTPUT.PUT_LINE( DATOS_PERSONA.SUELDO);
END;
/
  SELECT* FROM EMPLOYEES;
